// Catálogo Geral Estático de 100 Músicas (50 Nacionais e 50 Internacionais)
export const songsCatalog = [
  // --- NACIONAIS (1 a 50) ---
  { id: "br-1", title: "Evidências", artist: "Chitãozinho & Xororó", youtubeId: "Qfb1iMgkDxY", category: "Nacional", hasDemo: true },
  { id: "br-2", title: "Como Eu Quero", artist: "Kid Abelha", youtubeId: "qJ5YV9f44yM", category: "Nacional", hasDemo: true },
  { id: "br-3", title: "Fio de Cabelo", artist: "Chitãozinho & Xororó", youtubeId: "I_rE9r4d21g", category: "Nacional" },
  { id: "br-4", title: "Boate Azul", artist: "Joaquim & Manuel", youtubeId: "R-vK_M_K8_c", category: "Nacional" },
  { id: "br-5", title: "Eduardo e Mônica", artist: "Legião Urbana", youtubeId: "148Y72pUe3s", category: "Nacional" },
  { id: "br-6", title: "Tempo Perdido", artist: "Legião Urbana", youtubeId: "6-d2U9Yy4xM", category: "Nacional" },
  { id: "br-7", title: "Gostava Tanto de Você", artist: "Tim Maia", youtubeId: "q6hO1K0V09w", category: "Nacional" },
  { id: "br-8", title: "Não Quero Dinheiro", artist: "Tim Maia", youtubeId: "E07xK6s2l10", category: "Nacional" },
  { id: "br-9", title: "Infiel", artist: "Marília Mendonça", youtubeId: "j9M0_36X2cM", category: "Nacional" },
  { id: "br-10", title: "De Quem É A Culpa?", artist: "Marília Mendonça", youtubeId: "O9-114-16Ww", category: "Nacional" },
  { id: "br-11", title: "Amor I Love You", artist: "Marisa Monte", youtubeId: "g4Yh14c6X_I", category: "Nacional" },
  { id: "br-12", title: "Lanterna dos Afogados", artist: "Os Paralamas do Sucesso", youtubeId: "vB-R782QYac", category: "Nacional" },
  { id: "br-13", title: "Anna Julia", artist: "Los Hermanos", youtubeId: "R1O-R2P-1wE", category: "Nacional" },
  { id: "br-14", title: "Mulher de Fases", artist: "Raimundos", youtubeId: "c3OqU9E-kF8", category: "Nacional" },
  { id: "br-15", title: "O Sol", artist: "Jota Quest", youtubeId: "sD4qU_23vGg", category: "Nacional" },
  { id: "br-16", title: "Chove Chuva", artist: "Jorge Ben Jor", youtubeId: "3x9-V4g8w8M", category: "Nacional" },
  { id: "br-17", title: "Pais e Filhos", artist: "Legião Urbana", youtubeId: "3-F4oU87c88", category: "Nacional" },
  { id: "br-18", title: "Catedral", artist: "Zélia Duncan", youtubeId: "b8y1cW8_68g", category: "Nacional" },
  { id: "br-19", title: "Primeiros Erros", artist: "Capital Inicial", youtubeId: "4_R1u-qN-9M", category: "Nacional" },
  { id: "br-20", title: "À Sua Maneira", artist: "Capital Inicial", youtubeId: "1P2M82n383k", category: "Nacional" },
  { id: "br-21", title: "Trem Bala", artist: "Ana Vilela", youtubeId: "148u2pQ8X4k", category: "Nacional" },
  { id: "br-22", title: "Ouvi Dizer", artist: "Melim", youtubeId: "m1K-12p4_R8", category: "Nacional" },
  { id: "br-23", title: "Meu Abrigo", artist: "Melim", youtubeId: "18e9r2pU4Wk", category: "Nacional" },
  { id: "br-24", title: "Metamorfose Ambulante", artist: "Raul Seixas", youtubeId: "u_22p9U_q8M", category: "Nacional" },
  { id: "br-25", title: "Tente Outra Vez", artist: "Raul Seixas", youtubeId: "q18P3M9O1kM", category: "Nacional" },
  { id: "br-26", title: "Sozinho", artist: "Caetano Veloso", youtubeId: "c_3xO9k4X8g", category: "Nacional" },
  { id: "br-27", title: "Apenas um Rapaz Latino-Americano", artist: "Belchior", youtubeId: "14kQO9U8y88", category: "Nacional" },
  { id: "br-28", title: "Como Nossos Pais", artist: "Elis Regina", youtubeId: "c98P8U_q9kM", category: "Nacional" },
  { id: "br-29", title: "Garota de Ipanema", artist: "Tom Jobim", youtubeId: "u2p9V8q4_M8", category: "Nacional" },
  { id: "br-30", title: "Cheia de Manias", artist: "Raça Negra", youtubeId: "ePj8V-q48e8", category: "Nacional" },
  { id: "br-31", title: "Temporal", artist: "Art Popular", youtubeId: "zVq8U_9O2kW", category: "Nacional" },
  { id: "br-32", title: "Coração Radiante", artist: "Grupo Revelação", youtubeId: "3x9v8P4U-8k", category: "Nacional" },
  { id: "br-33", title: "Péssimo Negócio", artist: "Dilsinho", youtubeId: "c98P4U9Y_qk", category: "Nacional" },
  { id: "br-34", title: "Atrasadinha", artist: "Felipe Araújo", youtubeId: "z3x9P8O2-kM", category: "Nacional" },
  { id: "br-35", title: "Cerveja", artist: "Leandro & Leonardo", youtubeId: "vB3P8O9Y_qM", category: "Nacional" },
  { id: "br-36", title: "Pense em Mim", artist: "Leandro & Leonardo", youtubeId: "149O2pW-q8M", category: "Nacional" },
  { id: "br-37", title: "Evidências (Versão Pagode)", artist: "Exaltasamba", youtubeId: "v3x9P2U4-q8", category: "Nacional" },
  { id: "br-38", title: "Adocica", artist: "Beto Barbosa", youtubeId: "189P4U-q8Wk", category: "Nacional" },
  { id: "br-39", title: "Sandra Rosa Madalena", artist: "Sidney Magal", youtubeId: "c98V-p2O4kM", category: "Nacional" },
  { id: "br-40", title: "Milla", artist: "Netinho", youtubeId: "u2pW-O9U8yM", category: "Nacional" },
  { id: "br-41", title: "Eva", artist: "Banda Eva", youtubeId: "zV9P4U_q8Wk", category: "Nacional" },
  { id: "br-42", title: "Ralando o Tchan", artist: "É o Tchan", youtubeId: "148P-O9Y4Wk", category: "Nacional" },
  { id: "br-43", title: "Cose Della Vita", artist: "Eros Ramazzotti & Tina Turner", youtubeId: "ePj8P-O9Y4w", category: "Nacional" },
  { id: "br-44", title: "Garotos II", artist: "Leoni", youtubeId: "vB9P4U-q8eM", category: "Nacional" },
  { id: "br-45", title: "Por Você", artist: "Barão Vermelho", youtubeId: "3x9P-O2W4kM", category: "Nacional" },
  { id: "br-46", title: "Pro Dia Nascer Feliz", artist: "Cazuza", youtubeId: "c98P-O9U4eM", category: "Nacional" },
  { id: "br-47", title: "Exagerado", artist: "Cazuza", youtubeId: "149P-O9Y_qM", category: "Nacional" },
  { id: "br-48", title: "Codinome Beija-Flor", artist: "Cazuza", youtubeId: "u2pP-O9W4eM", category: "Nacional" },
  { id: "br-49", title: "Whisky a Go-Go", artist: "Roupa Nova", youtubeId: "zV9P-O9W4eM", category: "Nacional" },
  { id: "br-50", title: "Dona", artist: "Roupa Nova", youtubeId: "148P-O9W_qM", category: "Nacional" },

  // --- INTERNACIONAIS (51 a 100) ---
  { id: "en-1", title: "Bohemian Rhapsody", artist: "Queen", youtubeId: "fJ9rUzIMcZQ", category: "Internacional", hasDemo: true },
  { id: "en-2", title: "Can't Help Falling in Love", artist: "Elvis Presley", youtubeId: "vGJTaP5uqOU", category: "Internacional", hasDemo: true },
  { id: "en-3", title: "I Want It That Way", artist: "Backstreet Boys", youtubeId: "4fndeDfaWCg", category: "Internacional" },
  { id: "en-4", title: "Don't Stop Believin'", artist: "Journey", youtubeId: "VcjzHMhBtf0", category: "Internacional" },
  { id: "en-5", title: "Sweet Child O' Mine", artist: "Guns N' Roses", youtubeId: "1w7OgIMMRc4", category: "Internacional" },
  { id: "en-6", title: "Hotel California", artist: "Eagles", youtubeId: "h0G1ToJaHYy", category: "Internacional" },
  { id: "en-7", title: "Imagine", artist: "John Lennon", youtubeId: "YkgkThidqqy", category: "Internacional" },
  { id: "en-8", title: "Yesterday", artist: "The Beatles", youtubeId: "jo505VdHJaM", category: "Internacional" },
  { id: "en-9", title: "Let It Be", artist: "The Beatles", youtubeId: "QDYfEBY9NM4", category: "Internacional" },
  { id: "en-10", title: "Billie Jean", artist: "Michael Jackson", youtubeId: "Zi_XLOBDo_Y", category: "Internacional" },
  { id: "en-11", title: "Thriller", artist: "Michael Jackson", youtubeId: "sOnqjkJTMaA", category: "Internacional" },
  { id: "en-12", title: "Total Eclipse of the Heart", artist: "Bonnie Tyler", youtubeId: "lcOxhH8N3Bo", category: "Internacional" },
  { id: "en-13", title: "Take On Me", artist: "a-ha", youtubeId: "djV11Xbc914", category: "Internacional" },
  { id: "en-14", title: "Stayin' Alive", artist: "Bee Gees", youtubeId: "I_izvAbhQgY", category: "Internacional" },
  { id: "en-15", title: "Dancing Queen", artist: "ABBA", youtubeId: "xL3Y9e34WdM", category: "Internacional" },
  { id: "en-16", title: "Mamma Mia", artist: "ABBA", youtubeId: "unfzfe8f9S4", category: "Internacional" },
  { id: "en-17", title: "Creep", artist: "Radiohead", youtubeId: "XFkzRNyygfk", category: "Internacional" },
  { id: "en-18", title: "Wonderwall", artist: "Oasis", youtubeId: "6hzrDeceEKc", category: "Internacional" },
  { id: "en-19", title: "Losing My Religion", artist: "R.E.M.", youtubeId: "xwtdhWlaDxk", category: "Internacional" },
  { id: "en-20", title: "All Star", artist: "Smash Mouth", youtubeId: "L_jWHffIx5E", category: "Internacional" },
  { id: "en-21", title: "Zombie", artist: "The Cranberries", youtubeId: "b6oAFlPLo8w", category: "Internacional" },
  { id: "en-22", title: "My Heart Will Go On", artist: "Celine Dion", youtubeId: "WNIPqafd4As", category: "Internacional" },
  { id: "en-23", title: "Rolling in the Deep", artist: "Adele", youtubeId: "rYEDA3JcQdx", category: "Internacional" },
  { id: "en-24", title: "Someone Like You", artist: "Adele", youtubeId: "hLQl3WQQoQ0", category: "Internacional" },
  { id: "en-25", title: "Shape of You", artist: "Ed Sheeran", youtubeId: "JGwWNGJdvx8", category: "Internacional" },
  { id: "en-26", title: "Perfect", artist: "Ed Sheeran", youtubeId: "2Vv-BfVoq4g", category: "Internacional" },
  { id: "en-27", title: "Uptown Funk", artist: "Bruno Mars", youtubeId: "OPf0YbXqDm0", category: "Internacional" },
  { id: "en-28", title: "Just the Way You Are", artist: "Bruno Mars", youtubeId: "LjhCEMCw2Fk", category: "Internacional" },
  { id: "en-29", title: "Shallow", artist: "Lady Gaga & Bradley Cooper", youtubeId: "JPJJW1rYd1y", category: "Internacional" },
  { id: "en-30", title: "Bad Romance", artist: "Lady Gaga", youtubeId: "qrO4YZeyl0I", category: "Internacional" },
  { id: "en-31", title: "Love Story", artist: "Taylor Swift", youtubeId: "8xg3vE8Ie_E", category: "Internacional" },
  { id: "en-32", title: "Blank Space", artist: "Taylor Swift", youtubeId: "e-ORhEE9VVg", category: "Internacional" },
  { id: "en-33", title: "Stay", artist: "Rihanna", youtubeId: "JF8BRYnK2g0", category: "Internacional" },
  { id: "en-34", title: "Umbrella", artist: "Rihanna", youtubeId: "CvBfHwUxHIk", category: "Internacional" },
  { id: "en-35", title: "Viva La Vida", artist: "Coldplay", youtubeId: "dvgZkm1xWPE", category: "Internacional" },
  { id: "en-36", title: "Yellow", artist: "Coldplay", youtubeId: "yKNxeF4KMsY", category: "Internacional" },
  { id: "en-37", title: "In the End", artist: "Linkin Park", youtubeId: "eVTXPUF4Oz4", category: "Internacional" },
  { id: "en-38", title: "Numb", artist: "Linkin Park", youtubeId: "kXYiU_JCYtU", category: "Internacional" },
  { id: "en-39", title: "Smells Like Teen Spirit", artist: "Nirvana", youtubeId: "hTWKbfoikeg", category: "Internacional" },
  { id: "en-40", title: "It's My Life", artist: "Bon Jovi", youtubeId: "vx2u5uUu3DE", category: "Internacional" },
  { id: "en-41", title: "Livin' on a Prayer", artist: "Bon Jovi", youtubeId: "lDK9QqIzhwk", category: "Internacional" },
  { id: "en-42", title: "Fly Me to the Moon", artist: "Frank Sinatra", youtubeId: "mQR0bXO_yI8", category: "Internacional" },
  { id: "en-43", title: "My Way", artist: "Frank Sinatra", youtubeId: "qQzdAsjWGPg", category: "Internacional" },
  { id: "en-44", title: "Hallelujah", artist: "Jeff Buckley", youtubeId: "y8AWFf7EAc4", category: "Internacional" },
  { id: "en-45", title: "Stand by Me", artist: "Ben E. King", youtubeId: "hwZNL7AM9JE", category: "Internacional" },
  { id: "en-46", title: "Ain't No Sunshine", artist: "Bill Withers", youtubeId: "tIdIqbv7SPo", category: "Internacional" },
  { id: "en-47", title: "Careless Whisper", artist: "George Michael", youtubeId: "izGwDsrQ1eQ", category: "Internacional" },
  { id: "en-48", title: "Purple Rain", artist: "Prince", youtubeId: "TvnYmWp5_yM", category: "Internacional" },
  { id: "en-49", title: "Wake Me Up Before You Go-Go", artist: "Wham!", youtubeId: "mHHRN-wH8S0", category: "Internacional" },
  { id: "en-50", title: "Everybody (Backstreet's Back)", artist: "Backstreet Boys", youtubeId: "6M6samPEMpM", category: "Internacional" }
];

// Dados completos do UltraStar convertidos em JSON para Demonstração (Lazy Loaded Demos)
export const demoSongsNotes = {
  // Evidências - Chitãozinho & Xororó
  "br-1": {
    bpm: 124,
    gap: 14200, // milissegundos de silêncio inicial
    notes: [
      // Primeira estrofe
      { time: 14.5, duration: 0.4, pitch: 57, text: "Quan" },
      { time: 14.9, duration: 0.4, pitch: 57, text: "do" },
      { time: 15.3, duration: 0.4, pitch: 59, text: " eu" },
      { time: 15.7, duration: 0.4, pitch: 61, text: " di" },
      { time: 16.1, duration: 0.8, pitch: 59, text: "go" },
      { time: 17.0, duration: 0.4, pitch: 57, text: " que" },
      { time: 17.4, duration: 0.4, pitch: 57, text: " não" },
      { time: 17.8, duration: 0.4, pitch: 59, text: " que" },
      { time: 18.2, duration: 0.4, pitch: 61, text: "ro" },
      { time: 18.6, duration: 0.8, pitch: 59, text: " mais" },
      { time: 19.4, duration: 0.4, pitch: 57, text: " vo" },
      { time: 19.8, duration: 1.2, pitch: 57, text: "cê," },
      
      { time: 22.0, duration: 0.4, pitch: 57, text: " É" },
      { time: 22.4, duration: 0.4, pitch: 57, text: " por" },
      { time: 22.8, duration: 0.4, pitch: 59, text: "que" },
      { time: 23.2, duration: 0.4, pitch: 61, text: " eu" },
      { time: 23.6, duration: 0.8, pitch: 59, text: " te" },
      { time: 24.5, duration: 0.4, pitch: 57, text: " a" },
      { time: 24.9, duration: 0.4, pitch: 57, text: "mo" },
      { time: 25.3, duration: 0.4, pitch: 59, text: " pen" },
      { time: 25.7, duration: 0.4, pitch: 61, text: "san" },
      { time: 26.1, duration: 0.8, pitch: 59, text: "do" },
      { time: 26.9, duration: 0.4, pitch: 57, text: " em" },
      { time: 27.3, duration: 1.2, pitch: 54, text: " te" },
      { time: 28.5, duration: 1.0, pitch: 56, text: " ver," },

      // Refrão (E nessa loucura...)
      { time: 48.0, duration: 0.5, pitch: 61, text: " E" },
      { time: 48.5, duration: 0.5, pitch: 61, text: " nes" },
      { time: 49.0, duration: 0.5, pitch: 61, text: "sa" },
      { time: 49.5, duration: 0.5, pitch: 64, text: " lou" },
      { time: 50.0, duration: 0.8, pitch: 61, text: "cu" },
      { time: 50.8, duration: 1.0, pitch: 59, text: "ra" },
      { time: 52.0, duration: 0.5, pitch: 59, text: " de" },
      { time: 52.5, duration: 0.5, pitch: 59, text: " di" },
      { time: 53.0, duration: 0.5, pitch: 59, text: "zer" },
      { time: 53.5, duration: 0.5, pitch: 63, text: " que" },
      { time: 54.0, duration: 0.8, pitch: 59, text: " não" },
      { time: 54.8, duration: 1.0, pitch: 57, text: " te" },
      { time: 55.8, duration: 1.2, pitch: 57, text: " que" },
      { time: 57.0, duration: 1.5, pitch: 56, text: "ro," },

      { time: 59.0, duration: 0.5, pitch: 59, text: " Vou" },
      { time: 59.5, duration: 0.5, pitch: 59, text: " ne" },
      { time: 60.0, duration: 0.5, pitch: 59, text: "gan" },
      { time: 60.5, duration: 0.5, pitch: 63, text: "do" },
      { time: 61.0, duration: 0.8, pitch: 59, text: " as" },
      { time: 61.8, duration: 1.0, pitch: 57, text: " a" },
      { time: 63.0, duration: 0.5, pitch: 57, text: "pa" },
      { time: 63.5, duration: 0.5, pitch: 57, text: "ren" },
      { time: 64.0, duration: 0.5, pitch: 57, text: "cias" },
      { time: 64.5, duration: 0.5, pitch: 61, text: " mas" },
      { time: 65.0, duration: 0.8, pitch: 57, text: " não" },
      { time: 65.8, duration: 1.0, pitch: 56, text: " pos" },
      { time: 66.8, duration: 1.2, pitch: 56, text: "so" },
      { time: 68.0, duration: 1.5, pitch: 57, text: " com" },
      { time: 69.5, duration: 2.0, pitch: 57, text: "go." }
    ]
  },

  // Como Eu Quero - Kid Abelha
  "br-2": {
    bpm: 116,
    gap: 12000,
    notes: [
      { time: 12.1, duration: 0.5, pitch: 55, text: "Diz" },
      { time: 12.6, duration: 0.5, pitch: 55, text: " pra" },
      { time: 13.1, duration: 0.8, pitch: 57, text: " mim" },
      { time: 14.2, duration: 0.5, pitch: 55, text: " o" },
      { time: 14.7, duration: 0.5, pitch: 55, text: " que" },
      { time: 15.2, duration: 0.5, pitch: 57, text: " eu" },
      { time: 15.7, duration: 0.5, pitch: 59, text: " já" },
      { time: 16.2, duration: 1.0, pitch: 57, text: " sei" },
      
      { time: 18.0, duration: 0.5, pitch: 57, text: " Ten" },
      { time: 18.5, duration: 0.5, pitch: 57, text: "to" },
      { time: 19.0, duration: 0.8, pitch: 59, text: " ler" },
      { time: 20.0, duration: 0.5, pitch: 57, text: " o" },
      { time: 20.5, duration: 0.5, pitch: 57, text: " seu" },
      { time: 21.0, duration: 0.5, pitch: 59, text: " pen" },
      { time: 21.5, duration: 0.5, pitch: 60, text: "sa" },
      { time: 22.0, duration: 1.0, pitch: 59, text: "men" },
      { time: 23.0, duration: 1.5, pitch: 57, text: "to" },
      
      { time: 25.0, duration: 0.5, pitch: 59, text: " Mas" },
      { time: 25.5, duration: 0.5, pitch: 59, text: " vo" },
      { time: 26.0, duration: 0.8, pitch: 60, text: "cê" },
      { time: 27.0, duration: 0.5, pitch: 59, text: " sim" },
      { time: 27.5, duration: 0.5, pitch: 59, text: "ples" },
      { time: 28.0, duration: 0.5, pitch: 60, text: "men" },
      { time: 28.5, duration: 0.5, pitch: 62, text: "te" },
      { time: 29.0, duration: 1.5, pitch: 60, text: " foge" }
    ]
  },

  // Bohemian Rhapsody - Queen
  "en-1": {
    bpm: 72,
    gap: 2000,
    notes: [
      { time: 2.1, duration: 0.8, pitch: 58, text: "Is" },
      { time: 2.9, duration: 0.8, pitch: 60, text: " this" },
      { time: 3.7, duration: 0.8, pitch: 61, text: " the" },
      { time: 4.5, duration: 1.2, pitch: 60, text: " re" },
      { time: 5.7, duration: 1.2, pitch: 58, text: "al" },
      { time: 6.9, duration: 1.5, pitch: 58, text: " life?" },

      { time: 9.0, duration: 0.8, pitch: 58, text: " Is" },
      { time: 9.8, duration: 0.8, pitch: 60, text: " this" },
      { time: 10.6, duration: 0.8, pitch: 61, text: " just" },
      { time: 11.4, duration: 1.2, pitch: 60, text: " fan" },
      { time: 12.6, duration: 1.2, pitch: 58, text: "ta" },
      { time: 13.8, duration: 1.5, pitch: 58, text: "sy?" },

      { time: 16.0, duration: 0.8, pitch: 58, text: " Caught" },
      { time: 16.8, duration: 0.8, pitch: 60, text: " in" },
      { time: 17.6, duration: 0.8, pitch: 61, text: " a" },
      { time: 18.4, duration: 1.2, pitch: 61, text: " land" },
      { time: 19.6, duration: 1.2, pitch: 63, text: "slide," },
      
      { time: 21.0, duration: 0.8, pitch: 61, text: " No" },
      { time: 21.8, duration: 0.8, pitch: 60, text: " es" },
      { time: 22.6, duration: 0.8, pitch: 58, text: "cape" },
      { time: 23.4, duration: 0.8, pitch: 56, text: " from" },
      { time: 24.2, duration: 1.5, pitch: 58, text: " re" },
      { time: 25.7, duration: 2.0, pitch: 60, text: "al" },
      { time: 27.7, duration: 2.5, pitch: 58, text: "i" },
      { time: 30.2, duration: 3.0, pitch: 58, text: "ty." }
    ]
  },

  // Can't Help Falling in Love - Elvis Presley
  "en-2": {
    bpm: 68,
    gap: 8000,
    notes: [
      { time: 8.5, duration: 1.2, pitch: 55, text: "Wise" },
      { time: 10.2, duration: 1.2, pitch: 59, text: " men" },
      { time: 11.9, duration: 2.0, pitch: 62, text: " say," },
      
      { time: 14.5, duration: 1.2, pitch: 62, text: " on" },
      { time: 15.7, duration: 0.8, pitch: 64, text: "ly" },
      { time: 16.5, duration: 0.8, pitch: 62, text: " fools" },
      { time: 17.3, duration: 1.2, pitch: 60, text: " rush" },
      { time: 18.5, duration: 2.5, pitch: 59, text: " in." },
      
      { time: 21.5, duration: 1.2, pitch: 55, text: " But" },
      { time: 23.2, duration: 1.2, pitch: 57, text: " I" },
      { time: 24.9, duration: 0.8, pitch: 59, text: " can't" },
      { time: 25.7, duration: 0.8, pitch: 60, text: " help" },
      
      { time: 27.0, duration: 1.2, pitch: 59, text: " fal" },
      { time: 28.2, duration: 0.8, pitch: 57, text: "ling" },
      { time: 29.0, duration: 0.8, pitch: 55, text: " in" },
      { time: 29.8, duration: 1.2, pitch: 57, text: " love" },
      { time: 31.0, duration: 2.5, pitch: 59, text: " with" },
      { time: 33.5, duration: 3.5, pitch: 60, text: " you." }
    ]
  }
};
